# Site settings
title: Romain Péchayre 
email: rpechayr@gmail.com
description: "Romain Péchayre, co-founder and CTO at Applidget"

rich_description: 'Co-founder and CTO at <a href="http://www.applidget.com">Applidget</>'
baseurl: ""
url: "http://romain.pechayre.me"
twitter_username: rpechayr
github_username:  rpechayr

# Build settings
markdown: kramdown
permalink: pretty

exclude: ["Readme.md"]
